/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import static interfaz.Perfiles.sistema;
import java.util.Date;
import javax.swing.JOptionPane;
import mascota.Actividad;
import mascota.Sistema;

/**
 *
 * @author Emiliano
 */
public class BorrarActividad extends javax.swing.JFrame {

    Sistema sistema;
    Date fecha;
    public BorrarActividad(Sistema modelo,Date date) {
        initComponents();
        sistema = modelo;
        setLocationRelativeTo(null); 
        fecha = date;
        titulo.setText("Estas son las actividades del dia "+date.getDate()+"/"+date.getMonth()+"/"+date.getYear());
          String[] selections = new String[sistema.getListaActividades().size()];
        for (int i = 0; i < sistema.getListaActividades().size(); i++) {
            Actividad a = sistema.getListaActividades().get(i);
            if (sistema.fechasIguales(a.getFecha(), fecha)){
                  selections[i] = a.getDescripcion();
            }        
        }
        listaActividades.setListData(selections);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaActividades = new javax.swing.JList<>();
        titulo = new javax.swing.JLabel();
        borrarBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaActividades.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        listaActividades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaActividades);

        titulo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        titulo.setText("Lista de actividades del dia seleccionado");

        borrarBoton.setText("Borrar");
        borrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBotonActionPerformed(evt);
            }
        });

        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(salirBoton)
                        .addGap(198, 198, 198)
                        .addComponent(borrarBoton)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarBoton)
                    .addComponent(salirBoton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBotonActionPerformed
        String act = listaActividades.getSelectedValue();
        if (act!=null){
            System.out.println("Entrmoas");
            sistema.borrarActividadPorNombre(act);
        }else{
            JOptionPane.showMessageDialog(null, "Actividad sin seleccionar");
        }
    }//GEN-LAST:event_borrarBotonActionPerformed

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        Calendario c = new Calendario(sistema);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salirBotonActionPerformed

   
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBoton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaActividades;
    private javax.swing.JButton salirBoton;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
