
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import mascota.Familiar;
import mascota.Mascota;
import mascota.Sistema;

/**
 *
 * @author usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    static private Sistema sistema;
    private Familiar username;

    public VentanaPrincipal(Sistema modelo) {
        initComponents();
        sistema = modelo;
        //configuro usuario
        username = sistema.getUsuarioSeleccionado();
        UsernameLabel.setText(username.getNombre());
        ImagenUsuario.setIcon(username.getFoto());
        //configuro mascota
        int numeroMascotas = sistema.getListaMascotas().size();
        //porque se muestran las 4 primeras
        if (numeroMascotas > 4) {
            numeroMascotas = 4;
        }

        switch (numeroMascotas) {
            case 1:
                NombreMascota1.setText(sistema.getListaMascotas().get(0).getNombre());
                break;
            case 2:
                NombreMascota1.setText(sistema.getListaMascotas().get(0).getNombre());
                NombreMascota2.setText(sistema.getListaMascotas().get(1).getNombre());
                break;
            case 3:
                NombreMascota1.setText(sistema.getListaMascotas().get(0).getNombre());
                NombreMascota2.setText(sistema.getListaMascotas().get(1).getNombre());
                NombreMascota3.setText(sistema.getListaMascotas().get(2).getNombre());
                break;
            case 4:
                NombreMascota1.setText(sistema.getListaMascotas().get(0).getNombre());
                NombreMascota2.setText(sistema.getListaMascotas().get(1).getNombre());
                NombreMascota3.setText(sistema.getListaMascotas().get(2).getNombre());
                NombreMascota4.setText(sistema.getListaMascotas().get(3).getNombre());
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        perfilMascota1 = new javax.swing.JButton();
        borrarMascota1 = new javax.swing.JButton();
        NombreMascota1 = new javax.swing.JLabel();
        ImagenMascota1 = new javax.swing.JLabel();
        perfilMascota2 = new javax.swing.JButton();
        borrarMascota2 = new javax.swing.JButton();
        NombreMascota2 = new javax.swing.JLabel();
        ImagenMascota2 = new javax.swing.JLabel();
        borrarMascota3 = new javax.swing.JButton();
        perfilMascota3 = new javax.swing.JButton();
        NombreMascota3 = new javax.swing.JLabel();
        ImagenMascota3 = new javax.swing.JLabel();
        perfilMascota4 = new javax.swing.JButton();
        borrarMascota4 = new javax.swing.JButton();
        NombreMascota4 = new javax.swing.JLabel();
        ImagenMascota4 = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        perfilSeleccionBoton = new javax.swing.JButton();
        registrarMascota = new javax.swing.JButton();
        VeterinarioBoton = new javax.swing.JButton();
        calendarioBoton = new javax.swing.JButton();
        ImagenUsuario = new javax.swing.JLabel();
        ImagenDeFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        perfilMascota1.setBackground(new java.awt.Color(204, 255, 204));
        perfilMascota1.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jPanel1.add(perfilMascota1);
        perfilMascota1.setBounds(120, 390, 40, 10);

        borrarMascota1.setBackground(new java.awt.Color(255, 153, 153));
        borrarMascota1.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jPanel1.add(borrarMascota1);
        borrarMascota1.setBounds(160, 390, 20, 10);

        NombreMascota1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        NombreMascota1.setText("Nombre mascota 1");
        jPanel1.add(NombreMascota1);
        NombreMascota1.setBounds(100, 360, 120, 30);

        ImagenMascota1.setText("IMAGEN");
        jPanel1.add(ImagenMascota1);
        ImagenMascota1.setBounds(120, 300, 50, 30);

        perfilMascota2.setBackground(new java.awt.Color(204, 255, 204));
        perfilMascota2.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jPanel1.add(perfilMascota2);
        perfilMascota2.setBounds(270, 390, 40, 10);

        borrarMascota2.setBackground(new java.awt.Color(255, 153, 153));
        borrarMascota2.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jPanel1.add(borrarMascota2);
        borrarMascota2.setBounds(310, 390, 20, 10);

        NombreMascota2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        NombreMascota2.setText("Nombre mascota 2");
        jPanel1.add(NombreMascota2);
        NombreMascota2.setBounds(250, 360, 120, 30);

        ImagenMascota2.setText("IMAGEN");
        jPanel1.add(ImagenMascota2);
        ImagenMascota2.setBounds(270, 300, 50, 30);

        borrarMascota3.setBackground(new java.awt.Color(255, 153, 153));
        borrarMascota3.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jPanel1.add(borrarMascota3);
        borrarMascota3.setBounds(460, 390, 20, 10);

        perfilMascota3.setBackground(new java.awt.Color(204, 255, 204));
        perfilMascota3.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jPanel1.add(perfilMascota3);
        perfilMascota3.setBounds(420, 390, 40, 10);

        NombreMascota3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        NombreMascota3.setText("Nombre mascota 3");
        jPanel1.add(NombreMascota3);
        NombreMascota3.setBounds(400, 360, 120, 30);

        ImagenMascota3.setText("IMAGEN");
        jPanel1.add(ImagenMascota3);
        ImagenMascota3.setBounds(420, 300, 50, 30);

        perfilMascota4.setBackground(new java.awt.Color(204, 255, 204));
        perfilMascota4.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jPanel1.add(perfilMascota4);
        perfilMascota4.setBounds(570, 390, 40, 10);

        borrarMascota4.setBackground(new java.awt.Color(255, 153, 153));
        borrarMascota4.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jPanel1.add(borrarMascota4);
        borrarMascota4.setBounds(610, 390, 20, 10);

        NombreMascota4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        NombreMascota4.setText("Nombre mascota 4");
        jPanel1.add(NombreMascota4);
        NombreMascota4.setBounds(550, 360, 120, 30);

        ImagenMascota4.setText("IMAGEN");
        jPanel1.add(ImagenMascota4);
        ImagenMascota4.setBounds(570, 300, 50, 30);

        UsernameLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        UsernameLabel.setText("NOMBRE USUARIO");
        jPanel1.add(UsernameLabel);
        UsernameLabel.setBounds(60, 90, 110, 30);

        perfilSeleccionBoton.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        perfilSeleccionBoton.setText("Seleccionar Perfil");
        perfilSeleccionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilSeleccionBotonActionPerformed(evt);
            }
        });
        jPanel1.add(perfilSeleccionBoton);
        perfilSeleccionBoton.setBounds(20, 440, 150, 25);

        registrarMascota.setBackground(new java.awt.Color(204, 255, 255));
        registrarMascota.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        registrarMascota.setForeground(new java.awt.Color(0, 102, 102));
        registrarMascota.setText("Registrar mascota");
        registrarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMascotaActionPerformed(evt);
            }
        });
        jPanel1.add(registrarMascota);
        registrarMascota.setBounds(550, 440, 140, 25);

        VeterinarioBoton.setBackground(new java.awt.Color(153, 204, 255));
        VeterinarioBoton.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        VeterinarioBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/veterinaria.jpg"))); // NOI18N
        VeterinarioBoton.setMaximumSize(new java.awt.Dimension(10, 10));
        VeterinarioBoton.setMinimumSize(new java.awt.Dimension(5, 5));
        VeterinarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeterinarioBotonActionPerformed(evt);
            }
        });
        jPanel1.add(VeterinarioBoton);
        VeterinarioBoton.setBounds(430, 100, 120, 30);

        calendarioBoton.setBackground(new java.awt.Color(153, 204, 255));
        calendarioBoton.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        calendarioBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.jpg"))); // NOI18N
        calendarioBoton.setMaximumSize(new java.awt.Dimension(10, 10));
        calendarioBoton.setMinimumSize(new java.awt.Dimension(5, 5));
        calendarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarioBotonActionPerformed(evt);
            }
        });
        jPanel1.add(calendarioBoton);
        calendarioBoton.setBounds(300, 100, 120, 30);

        ImagenUsuario.setText("Imagen Usuario (el texto se borra)");
        jPanel1.add(ImagenUsuario);
        ImagenUsuario.setBounds(40, 40, 170, 14);

        ImagenDeFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dog summer.jpg"))); // NOI18N
        jPanel1.add(ImagenDeFondo);
        ImagenDeFondo.setBounds(0, 0, 950, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calendarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarioBotonActionPerformed
        Calendario calendario = new Calendario(sistema);
        calendario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_calendarioBotonActionPerformed

    private void VeterinarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeterinarioBotonActionPerformed
        Veterinaria vet = new Veterinaria(sistema);
        vet.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VeterinarioBotonActionPerformed

    private void registrarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMascotaActionPerformed
        AltaMascota altaMascota = new AltaMascota(sistema);
        altaMascota.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarMascotaActionPerformed

    private void perfilSeleccionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilSeleccionBotonActionPerformed
        Perfiles perfiles = new Perfiles(sistema);
        perfiles.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_perfilSeleccionBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //   new VentanaPrincipal(sistema,username).setVisible(true);.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenDeFondo;
    private javax.swing.JLabel ImagenMascota1;
    private javax.swing.JLabel ImagenMascota2;
    private javax.swing.JLabel ImagenMascota3;
    private javax.swing.JLabel ImagenMascota4;
    private javax.swing.JLabel ImagenUsuario;
    private javax.swing.JLabel NombreMascota1;
    private javax.swing.JLabel NombreMascota2;
    private javax.swing.JLabel NombreMascota3;
    private javax.swing.JLabel NombreMascota4;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JButton VeterinarioBoton;
    private javax.swing.JButton borrarMascota1;
    private javax.swing.JButton borrarMascota2;
    private javax.swing.JButton borrarMascota3;
    private javax.swing.JButton borrarMascota4;
    private javax.swing.JButton calendarioBoton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton perfilMascota1;
    private javax.swing.JButton perfilMascota2;
    private javax.swing.JButton perfilMascota3;
    private javax.swing.JButton perfilMascota4;
    private javax.swing.JButton perfilSeleccionBoton;
    private javax.swing.JButton registrarMascota;
    // End of variables declaration//GEN-END:variables
}

